import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // BlueWILL Core Palette
        navy: {
          50: '#e8edf5',
          100: '#c5d1e8',
          200: '#9fb2d8',
          300: '#7893c8',
          400: '#587dbc',
          500: '#3867b0',
          600: '#2c5499',
          700: '#1e3e7b',
          800: '#122960',
          900: '#0a1b45',
          950: '#060f2a',
        },
        slate_blue: {
          50: '#eef0f8',
          100: '#d4d9ee',
          200: '#b7bee3',
          300: '#98a3d7',
          400: '#7f8ece',
          500: '#6678c5',
          600: '#4e5fb5',
          700: '#3a489e',
          800: '#2a3480',
          900: '#1c2360',
        },
        cyan: {
          50: '#e0fbff',
          100: '#b3f5ff',
          200: '#7eedff',
          300: '#45e4ff',
          400: '#00d9ff',
          500: '#00c4e8',
          600: '#009dba',
          700: '#007a90',
          800: '#005a6b',
          900: '#003d4a',
        },
        sunset: {
          50: '#fff1ee',
          100: '#ffd9d0',
          200: '#ffb9a8',
          300: '#ff9278',
          400: '#ff6b47',
          500: '#ff4520',
          600: '#e83000',
          700: '#c02600',
          800: '#971e00',
          900: '#6e1600',
        },
        canary: {
          50: '#fffde0',
          100: '#fffab3',
          200: '#fff680',
          300: '#fff24a',
          400: '#ffed1a',
          500: '#ffe000',
          600: '#d4b800',
          700: '#a88f00',
          800: '#7c6800',
          900: '#504200',
        },
        emerald: {
          50: '#e0faf0',
          100: '#b3f2d9',
          200: '#7ae8bf',
          300: '#3ddba3',
          400: '#00cf8a',
          500: '#00b876',
          600: '#009860',
          700: '#007a4c',
          800: '#005c38',
          900: '#003d25',
        },
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Poppins', 'system-ui', 'sans-serif'],
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'willy-gradient': 'linear-gradient(135deg, #1e3e7b 0%, #0a1b45 25%, #00c4e8 50%, #3a489e 75%, #060f2a 100%)',
        'hero-gradient': 'linear-gradient(135deg, #060f2a 0%, #1e3e7b 50%, #0a1b45 100%)',
        'card-gradient': 'linear-gradient(135deg, rgba(30,62,123,0.9) 0%, rgba(6,15,42,0.95) 100%)',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-down': {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'bounce-icon': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-4px)' },
        },
        'thunder-streak': {
          '0%': { transform: 'translateY(0) scaleY(1)', opacity: '1' },
          '50%': { transform: 'translateY(-15px) scaleY(1.3)', opacity: '0.8' },
          '100%': { transform: 'translateY(-25px) scaleY(0)', opacity: '0' },
        },
        'willy-flow': {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 5px rgba(0,196,232,0.4)' },
          '50%': { boxShadow: '0 0 20px rgba(0,196,232,0.8), 0 0 40px rgba(0,196,232,0.4)' },
        },
        'scroll-x': {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'press-3d': {
          '0%': { transform: 'translateY(0)', boxShadow: '0 4px 0 0 var(--btn-shadow)' },
          '100%': { transform: 'translateY(4px)', boxShadow: '0 0 0 0 var(--btn-shadow)' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        'scale-in': {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'shimmer': 'shimmer 1.5s infinite linear',
        'slide-up': 'slide-up 0.4s ease-out',
        'slide-down': 'slide-down 0.3s ease-out',
        'fade-in': 'fade-in 0.3s ease-out',
        'bounce-icon': 'bounce-icon 0.4s ease-in-out',
        'thunder-streak': 'thunder-streak 0.5s ease-out forwards',
        'willy-flow': 'willy-flow 6s ease infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'scroll-x': 'scroll-x 30s linear infinite',
        'float': 'float 3s ease-in-out infinite',
        'scale-in': 'scale-in 0.2s ease-out',
      },
      boxShadow: {
        '3d-btn': '0 4px 0 0 rgba(0,0,0,0.3)',
        '3d-btn-sunset': '0 4px 0 0 #c02600',
        '3d-btn-navy': '0 4px 0 0 #0a1b45',
        '3d-btn-cyan': '0 4px 0 0 #007a90',
        'glass': '0 8px 32px rgba(0,0,0,0.2), inset 0 0 0 1px rgba(255,255,255,0.1)',
        'card-hover': '0 20px 60px rgba(0,0,0,0.3)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
export default config;
